package com.visual.blackjack.modelo;

public class Carta {
	private static String[] imagenCarta = {
			"Recursos/corazon2.png",
			"Recursos/corazon3.png",
			"Recursos/corazon4.png",
            "Recursos/corazon5.png",
            "Recursos/corazon6.png",
            "Recursos/corazon7.png",
            "Recursos/corazon8.png",
            "Recursos/corazon9.png",
            "Recursos/corazon10.png",
            "Recursos/corazonJ.png",
            "Recursos/corazonQ.png",
            "Recursos/corazonK.png",
            "Recursos/corazonA.png",
            "Recursos/trebol2.png",
        	"Recursos/trebol3.png",
			"Recursos/trebol4.png",
            "Recursos/trebol5.png",
            "Recursos/trebol6.png",
            "Recursos/trebol7.png",
            "Recursos/trebol8.png",
            "Recursos/trebol9.png",
            "Recursos/trebol10.png",
            "Recursos/trebolJ.png",
            "Recursos/trebolQ.png",
            "Recursos/trebolK.png",
            "Recursos/trebolA.png",
            "Recursos/diamante2.png",
        	"Recursos/diamante3.png",
			"Recursos/diamante4.png",
            "Recursos/diamante5.png",
            "Recursos/diamante6.png",
            "Recursos/diamante7.png",
            "Recursos/diamante8.png",
            "Recursos/diamante9.png",
            "Recursos/diamante10.png",
            "Recursos/diamanteJ.png",
            "Recursos/diamanteQ.png",
            "Recursos/diamanteK.png",
            "Recursos/diamanteA.png",
            "Recursos/picas2.png",
        	"Recursos/picas3.png",
			"Recursos/picas4.png",
            "Recursos/picas5.png",
            "Recursos/picas6.png",
            "Recursos/picas7.png",
            "Recursos/picas8.png",
            "Recursos/picas9.png",
            "Recursos/picas10.png",
            "Recursos/picasJ.png",
            "Recursos/picasQ.png",
            "Recursos/picasK.png",
            "Recursos/picasA.png"
            };
	private static int[] valorCarta = {
			2,
			3,
			4,
			5,
			6,
			7,
			8,
			9,
			10,
			10,
			10,
			10,
			11,
			2,
			3,
			4,
			5,
			6,
			7,
			8,
			9,
			10,
			10,
			10,
			10,
			11,
			2,
			3,
			4,
			5,
			6,
			7,
			8,
			9,
			10,
			10,
			10,
			10,
			11,
			2,
			3,
			4,
			5,
			6,
			7,
			8,
			9,
			10,
			10,
			10,
			10,
			11
            };
	
	public static String getImagen(int numero) {
		String imagen;
		imagen = imagenCarta[numero];
		return imagen;
	}
	
	public static int getValor(int numero) {
		int valor;
		valor = valorCarta[numero];
		return valor;
	}

}
